@startuml actDiagram
|Guest|
start
:Masukkan Kode RSVP;
:Diarsipkan ke Page Form RSVP;
:Isi Form RSVP;
:Form RSVP terdiri dari:
- Nama
- Email
- Phone
- Bawa Tamu Berapa
- Komen/Ucapan Selamat;
:Submit Form RSVP;
:Data Dikirim ke Database;
stop

|Admin|
start
:Melihat Dashboard Data Tamu;
:Melihat Total Tamu yang Isi RSVP;
:Melihat Total Tamu yang Hadir di Acara;
:Ekspor File Data Tamu;
:Impor File Data Tamu;
:Edit Data Tamu;
:Hapus Data Tamu;
:Hapus Semua Data Tamu;
:Menambahkan Tamu Baru;
:Melihat Komen/Ucapan Selamat;
:Hapus Komen Tamu;
stop
@enduml